Repository Xisabla/fingerlib, pull requests merged in 2022-05, with the labels that each got.

#10 Add faup build step in github workflow
  .github/workflows/build-and-test.yaml
  test/basic.cpp
Labels: enhancement, library

#7 Use Faup functions instead of POCO. Closes #3
  .github/workflows/build-and-test.yaml
  Makefile
  include/finger/fingerprint.hpp
  src/fingerprint.cpp
  test/basic.cpp
Labels: enhancement, library

#8 feat(tests): test dataset helpers
  .github/workflows/build-and-test.yaml
  Makefile
  include/test/dataset.hpp
  test/basic.cpp
  test/common/dataset.cpp
  test/data/dataset_basic.json
  test/data/hfinger_samples.json
Labels: enhancement

#13 feat(server): add server docker image
  .github/workflows/build-docker.yaml
  .github/workflows/build-test-library.yaml
  .gitignore
  README.md
  server/Dockerfile
  server/run.sh
Labels: enhancement, dataset

#14 fix(server): fix python script and output directory rights
  README.md
  requirements.txt
  script/pcap_to_json.py
  server/Dockerfile
  server/run.sh
Labels: enhancement, dataset

#15 Rework and add python script to convert data from pcap to usable datasets in library testing
  .gitignore
  requirements.txt
  script/json_to_test_dataset.py
  script/pcap_to_json.py
  test/basic.cpp
  test/data/dataset_full.json
Labels: enhancement, dataset, library

#16 Complete fingerprint computation
  .clang-tidy
  .gitignore
  include/finger/configs.hpp
  include/finger/fingerprint.hpp
  include/finger/utils.hpp
  include/json.hpp
  requirements.txt
  script/json_to_test_dataset.py
  script/pcap_to_json.py
  src/fingerprint.cpp
  test/basic.cpp
  test/data/dataset_basic.json
  test/data/dataset_full.json
  test/data/hfinger_samples.json
Labels: enhancement, library

#18 Add release workflow on master
  .github/workflows/build-test-library.yaml
  Makefile
  include/finger/configs.hpp
  include/finger/fingerprint.hpp
  include/test/dataset.hpp
  src/fingerprint.cpp
  test/basic.cpp
  test/common/dataset.cpp
Labels: enhancement

#9 First release
  .clang-tidy
  .github/workflows/build-docker.yaml
  .github/workflows/build-test-library.yaml
  .gitignore
  Makefile
  README.md
  include/configs.hpp
  include/finger/configs.hpp
  include/finger/fingerprint.hpp
  include/finger/utils.hpp
  include/json.hpp
  include/test/dataset.hpp
  requirements.txt
  script/json_to_test_dataset.py
  script/pcap_to_json.py
  server/Dockerfile
  server/run.sh
  src/fingerprint.cpp
  test/basic.cpp
  test/common/dataset.cpp
  test/data/dataset_basic.json
  test/data/dataset_full.json
Labels: release
